### ISSUE TITLE
CsvExtractor (FileExtractorAbstract) carrier reference in extract()

### ISSUE THREAD

**Issue by zodimo** [fab2s/YaEtl#10]
Hi 

I am unable to use the CsvExtractor as indicated in the documentation.
// standalone
foreach($csvExtractor->getTraversable() as $record) {
    // do something with $record array
}

I get the following error.
Error: Call to a member function getFlowMap() on null

**Comment by fab2s** [comment]
Hello,
This is part of what v2 has fixed, it is pretty stable now (used in production) and I will release it as soon as I find the time to do it.

Until then, you can replace this line : 
```php
$this->getCarrier()->getFlowMap()->incrementNode($this->getId(), 'num_extract');
```

with : 
```php
$this->getCarrier() && $this->getCarrier()->getFlowMap()->incrementNode($this->getId(), 'num_extract');
```
here https://github.com/fab2s/YaEtl/blob/549b593bd130458d9853871f72b0ad4e57e529b3/src/Extractors/File/FileExtractorAbstract.php#L45
