### ISSUE TITLE
DbExtractor ignores/"rewrites" parameters

### ISSUE THREAD

**Issue by cxj** [fab2s/YaEtl#12]
I want to do queries like this:
```php
$extract = DB::table('mytable')
    ->select(['item', 'rank'])
    ->where('item', 'LIKE', 'J%')
    ->orderBy('rank')
    ->take(500);`
```
Which will return the top 500 ranked items named `J*`.

Except when `DbExtractor` executes this query, it replaces my bindings in the `where` clause and tries to bind some missing parameter.  It also completely ignores the limited number of items in the `take` clause, and tries to chunk the query result.

Do I need to write my own version of `DbExtractor`, or am I just not understanding how to correctly use it?  Can it be made to do what I want?

**Comment by fab2s** [comment]
Hello,

The `take` on the query builder call should be replaced by a `limit` on the yaetl instance. Yaetl DB extractor extends from `extractorLimitAbstract `and `extractorBatchLimitAbstract` which provides with methods to limit the number of records extracted as well as setting a batchsize and an offset.

Just set the desired limit on your instance before you call `exec` and you will get the proper behavior.

**Comment by cxj** [comment]
I think you meant `DbExtractor::setLimit()` because none of the objects involved have a `limit()` method.

**Comment by cxj** [comment]
I've got it working the way I want using `setLimit()`.  Thanks.
